CREATE TABLE ORDER_DATA(
ORDER_ID BIGSERIAL PRIMARY KEY,
USER_ID BIGINT NOT NULL,
DELIVERER_ID BIGINT,
ORDER_STATE VARCHAR(26) NOT NULL,
DELIVERY_LOCATION VARCHAR(26) NOT NULL,
STORE_ID BIGINT NOT NULL,
ITEM_ID BIGINT NOT NULL
);


