CREATE TABLE PERSON(
PERSON_ID SERIAL PRIMARY KEY,
FIRST_NAME VARCHAR(64),
LAST_NAME VARCHAR(64),
EMAIL VARCHAR(64)
);

CREATE TABLE USER_DATA(
  USER_ID BIGSERIAL PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  USER_NAME VARCHAR(64),
  PASSWORD VARCHAR(64),
  CREATED_AT VARCHAR(14),
  UPDATED_AT VARCHAR(14),
  ADDRESS VARCHAR(64),
  PHONE_NUMBER VARCHAR(24)
);


CREATE TABLE USER_AUTHORITY(
  TYPE_ID BIGSERIAL PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  USER_TYPE VARCHAR(26) NOT NULL
);

